
// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A travel itinerary generation AI agent.
 *
 * - generateItinerary - A function that handles the travel itinerary generation process.
 * - GenerateItineraryInput - The input type for the generateItinerary function.
 * - GenerateItineraryOutput - The return type for the generateItinerary function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateItineraryInputSchema = z.object({
  destination: z.string().describe('The desired travel destination.'),
  interests: z.string().describe('A comma-separated list of interests and activities.'),
  currency: z.string().describe('The preferred currency for budget calculations (e.g., USD, EUR).'),
  budgetAmount: z.number().describe('The budget amount for the trip.'),
  duration: z.number().describe('The duration of the trip in days.'),
});
export type GenerateItineraryInput = z.infer<typeof GenerateItineraryInputSchema>;

const GenerateItineraryOutputSchema = z.object({
  itinerary: z.string().describe('A detailed day-by-day travel itinerary in human-readable text format.'),
});
export type GenerateItineraryOutput = z.infer<typeof GenerateItineraryOutputSchema>;

export async function generateItinerary(input: GenerateItineraryInput): Promise<GenerateItineraryOutput> {
  return generateItineraryFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateItineraryPrompt',
  input: {schema: GenerateItineraryInputSchema},
  output: {schema: GenerateItineraryOutputSchema},
  prompt: `You are a travel expert. Your task is to generate a personalized travel itinerary.

First, review the provided 'Destination': {{{destination}}}.
If the destination seems misspelled, ambiguous (e.g., a general country name instead of a city), or unclear, please use your knowledge to infer the most likely specific, well-known travel destination. For example, if 'Parris' is provided, assume 'Paris, France'. If 'US' is provided, you might choose a major city like 'New York City, USA' or state that more specificity is needed if you cannot confidently choose.

If you make such a correction or assumption, please clearly state the destination you are generating the itinerary for at the very beginning of the 'Overview' section. For example: "Overview: This itinerary is for Paris, France. A 5-day trip focusing on..."

Then, generate the itinerary based on this (potentially corrected) destination and the following user preferences:
Interests: {{{interests}}}
Currency: {{{currency}}}
Budget: {{{budgetAmount}}} {{{currency}}}
Duration: {{{duration}}} days

Create a detailed day-by-day itinerary including:
- Suggested activities and attractions
- Food recommendations (mention types of cuisine or specific restaurants if possible)
- Hotel suggestions (mention types of hotels or specific examples if possible)
- Local tips and advice (e.g., transportation, safety, etiquette)

IMPORTANT: Present the entire itinerary as a continuous block of human-readable text. Do NOT format the output as a JSON object.
Use a main heading for "Overview" and for each day (e.g., "Day 1: Arrival and Exploration").
Within each day, use sub-headings (e.g., "Activities:", "Food:", "Hotel Suggestions:", "Local Tips:") or bullet points for details.

Example Structure:

Overview:
(If a correction was made, start with "This itinerary is for [Corrected Destination Name].") A brief summary of the trip, highlighting key experiences.

Day 1: Arrival and City Exploration
Activities:
- Arrive at the destination, check into your hotel.
- Take a walking tour of the city center.
- Visit [Main Historical Site].
Food:
- Lunch at [Restaurant Name] (cuisine type).
- Dinner at [Restaurant Name] (cuisine type).
Hotel Suggestions:
- [Hotel Name 1] (style, price range)
- [Hotel Name 2] (style, price range)
Local Tips:
- Purchase a local transport card for easy travel.

Day 2: Cultural Immersion
Activities:
- Visit [Museum Name].
- Explore [Local Market].
Food:
- Try local street food for lunch.
- Fine dining experience at [Restaurant Name].
Hotel Suggestions:
- [Hotel Name example]
Local Tips:
- [Tip example]

...and so on for all {{{duration}}} days.

Ensure the output is a single block of text with clear formatting as described.
`,
});

const generateItineraryFlow = ai.defineFlow(
  {
    name: 'generateItineraryFlow',
    inputSchema: GenerateItineraryInputSchema,
    outputSchema: GenerateItineraryOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);

