
// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A travel itinerary generation AI agent.
 *
 * - generateItinerary - A function that handles the travel itinerary generation process.
 * - GenerateItineraryInput - The input type for the generateItinerary function.
 * - GenerateItineraryOutput - The return type for the generateItinerary function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateItineraryInputSchema = z.object({
  destination: z.string().describe('The desired travel destination.'),
  interests: z.string().describe('A comma-separated list of interests and activities.'),
  currency: z.string().describe('The preferred currency for budget calculations (e.g., USD, EUR).'),
  budgetAmount: z.number().describe('The budget amount for the trip.'),
  duration: z.number().describe('The duration of the trip in days.'),
});
export type GenerateItineraryInput = z.infer<typeof GenerateItineraryInputSchema>;

const GenerateItineraryOutputSchema = z.object({
  itinerary: z.string().describe('A detailed day-by-day travel itinerary in human-readable text format.'),
});
export type GenerateItineraryOutput = z.infer<typeof GenerateItineraryOutputSchema>;

export async function generateItinerary(input: GenerateItineraryInput): Promise<GenerateItineraryOutput> {
  return generateItineraryFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateItineraryPrompt',
  input: {schema: GenerateItineraryInputSchema},
  output: {schema: GenerateItineraryOutputSchema},
  prompt: `You are a travel expert. Generate a personalized travel itinerary based on the following information:

Destination: {{{destination}}}
Interests: {{{interests}}}
Currency: {{{currency}}}
Budget: {{{budgetAmount}}} {{{currency}}}
Duration: {{{duration}}} days

Create a detailed day-by-day itinerary including:
- Suggested activities and attractions
- Food recommendations
- Hotel suggestions
- Local tips and advice

IMPORTANT: Present the itinerary as a continuous block of human-readable text. Do NOT format the output as a JSON object.
Use headings for days (e.g., "Day 1: Arrival and Exploration") and sub-headings (e.g., "Activities:", "Food:", "Hotel Suggestions:", "Local Tips:") or bullet points for details within each day.

For example:

Overview:
A brief summary of the trip.

Day 1: Arrival and City Exploration
Activities:
- Arrive at the destination, check into your hotel.
- Take a walking tour of the city center.
- Visit the main historical site.
Food:
- Lunch at [Restaurant Name] (cuisine type).
- Dinner at [Restaurant Name] (cuisine type).
Hotel Suggestions:
- [Hotel Name 1] (style, price range)
- [Hotel Name 2] (style, price range)
Local Tips:
- Purchase a local transport card for easy travel.

Day 2: Cultural Immersion
Activities:
- Visit [Museum Name].
- Explore [Local Market].
Food:
- Try local street food for lunch.
- Fine dining experience at [Restaurant Name].
...and so on for all days.

Ensure the output is a single block of text with clear formatting as described.
`,
});

const generateItineraryFlow = ai.defineFlow(
  {
    name: 'generateItineraryFlow',
    inputSchema: GenerateItineraryInputSchema,
    outputSchema: GenerateItineraryOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
