// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A travel itinerary generation AI agent.
 *
 * - generateItinerary - A function that handles the travel itinerary generation process.
 * - GenerateItineraryInput - The input type for the generateItinerary function.
 * - GenerateItineraryOutput - The return type for the generateItinerary function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateItineraryInputSchema = z.object({
  destination: z.string().describe('The desired travel destination.'),
  interests: z.string().describe('A comma-separated list of interests and activities.'),
  currency: z.string().describe('The preferred currency for budget calculations (e.g., USD, EUR).'),
  budgetAmount: z.number().describe('The budget amount for the trip.'),
  duration: z.number().describe('The duration of the trip in days.'),
});
export type GenerateItineraryInput = z.infer<typeof GenerateItineraryInputSchema>;

const GenerateItineraryOutputSchema = z.object({
  itinerary: z.string().describe('A detailed day-by-day travel itinerary.'),
});
export type GenerateItineraryOutput = z.infer<typeof GenerateItineraryOutputSchema>;

export async function generateItinerary(input: GenerateItineraryInput): Promise<GenerateItineraryOutput> {
  return generateItineraryFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateItineraryPrompt',
  input: {schema: GenerateItineraryInputSchema},
  output: {schema: GenerateItineraryOutputSchema},
  prompt: `You are a travel expert. Generate a personalized travel itinerary based on the following information:

Destination: {{{destination}}}
Interests: {{{interests}}}
Currency: {{{currency}}}
Budget: {{{budgetAmount}}} {{{currency}}}
Duration: {{{duration}}} days

Create a detailed day-by-day itinerary including:
- Suggested activities and attractions
- Food recommendations
- Hotel suggestions
- Local tips and advice`,
});

const generateItineraryFlow = ai.defineFlow(
  {
    name: 'generateItineraryFlow',
    inputSchema: GenerateItineraryInputSchema,
    outputSchema: GenerateItineraryOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
